Dasher/Models/Note.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dasher.Models
{
    public class Note
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Topic { get; set; }

        public string Description { get; set; }

        public string Username { get; set; }
    }
}

Dasher/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dasher.Models
{
    public class User
    {
        public int Id { get; set; }

        public string Fullname { get; set; }

        public string Username { get; set; }

        public string Password { get; set; }

        public string Role { get; set; }

        public DateTime Created { get; set; }
    }
}

Dasher/Controllers/NoteController.cs
using Dasher.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Dasher.Controllers
{
    [Authorize(AuthenticationSchemes = "UserSecurity")]
    public class NoteController : Controller
    {
        private List<Note> notes = DBUtl.GetList<Note>(@"SELECT * FROM notes");

        public IActionResult Index()
        {
            ViewData["CurrentUsername"] = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            return View(notes);
        }
    }
}

Dasher/Controllers/ScrapeController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Dasher.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using HtmlAgilityPack;
using System.Dynamic;

namespace Dasher.Controllers
{
    [Authorize(AuthenticationSchemes = "UserSecurity")]
    public class ScrapeController : Controller
    {
        private static dynamic getModel()
        {
            List<Website> websites = DBUtl.GetList<Website>("SELECT * FROM websites");
            List<Supermarket> supermarkets = DBUtl.GetList<Supermarket>("SELECT * FROM supermarkets");

            dynamic model = new ExpandoObject();
            model.Website = websites;
            model.Supermarket = supermarkets;

            return model;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View(getModel()); 
        }

        [Authorize]
        public IActionResult Source(int id)
        {
            List<Website> websites = DBUtl.GetList<Website>("SELECT * FROM websites WHERE Id={0}", id);
            var url = websites[0].Url;
            var company = websites[0].Company;

            string delete = "DELETE FROM supermarkets WHERE Retailer='{0}'";
            DBUtl.ExecSQL(delete, company);

            HtmlWeb web = new HtmlWeb();
            var htmlDocument = web.Load(url);
            var categories = htmlDocument.DocumentNode.SelectNodes("//ul[@data-testid='categoryContainer']//p");
            var categoriesURL = htmlDocument.DocumentNode.SelectNodes("//ul[@data-testid='categoryContainer']//span/@href");
            var subCategoriesURL = htmlDocument.DocumentNode.SelectNodes("//ul[@data-testid='subCategory']//a/@href");

            List<string> lstCategory = new List<string>();
            List<string> lstCategoryURL = new List<string>();
            List<string> lstSubCategoryURL = new List<string>();

            string retailer = "NTUC FairPrice";
            string str = "";

            if (categories != null)
            {
                foreach (var category in categories)
                {
                    lstCategory.Add(SetUCase(category.InnerText.Replace("&amp;", "&")));
                }
            }

            if (categoriesURL != null)
            {
                foreach (var categoryURL in categoriesURL)
                {
                    lstCategoryURL.Add("https://www.fairprice.com.sg" + categoryURL.Attributes["href"].Value);
                }
            }

            if (subCategoriesURL != null)
            {
                foreach (var subCategoryURL in subCategoriesURL)
                {
                    lstSubCategoryURL.Add("https://www.fairprice.com.sg" + subCategoryURL.Attributes["href"].Value);
                }
            }

            int countSub = 0;          
            for (int count = 0; count < lstCategory.Count(); count++)
            {
                var subCategories = htmlDocument.DocumentNode.SelectNodes(string.Format("//li[@order='{0}']//a", count));
                if (subCategories != null)
                {
                    bool first = true;
                    foreach (var subCategory in subCategories)
                    {
                        str = SetUCase(subCategory.InnerText.Replace("&amp;", "&"));                     
                        string insert = @"INSERT INTO supermarkets (Retailer, Category, SubCategory, Url)
                                    VALUE ('{0}', '{1}', '{2}', '{3}')";

                        if (count == 0 && first)
                        {
                            DBUtl.ExecSQL(insert, retailer, lstCategory[count], "View All", lstCategoryURL[count]);
                            DBUtl.ExecSQL(insert, retailer, lstCategory[count], str, lstSubCategoryURL[countSub]);
                            first = false;
                            countSub++;                          
                        }
                        else if (first)
                        {
                            DBUtl.ExecSQL(insert, retailer, lstCategory[count], str, lstCategoryURL[count]);
                            first = false;
                        }
                        else
                        {
                            if (str != "Infant Formula")
                            {
                                DBUtl.ExecSQL(insert, retailer, lstCategory[count], str, lstSubCategoryURL[countSub]);
                                countSub++;
                            }
                        }
                    }
                }
            }

            string update = "UPDATE websites SET LastScraped = NOW() WHERE Id={0}";
            DBUtl.ExecSQL(update, id);

            return View("Index", getModel());
        }

        public static string SetUCase(string unformattedString)
        {
            string formattedString = "";

            foreach (var s in unformattedString.Split(" "))
            {
                if (s.Length == 0)
                {
                    formattedString += s;
                }
                else if (s.Length == 1)
                {
                    formattedString += char.ToUpper(s[0]);
                }
                else
                {
                    formattedString += char.ToUpper(s[0]) + s.Substring(1);
                }
                formattedString += " ";
            }
            return formattedString.Trim();
        }
    }
}

Dasher/Controllers/SourceController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Dasher.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using HtmlAgilityPack;

namespace Dasher.Controllers
{
    [Authorize(AuthenticationSchemes = "UserSecurity")]
    public class SourceController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Supermarket()
        {
            List<Supermarket> supermarket = DBUtl.GetList<Supermarket>("SELECT DISTINCT Retailer FROM supermarkets");
            ViewData["retailers"] = new SelectList(supermarket, "Retailer", "Retailer");

            return View();
        }

        [Authorize]
        public IActionResult GetSource(string id)
        {
            string category = id.Split("*")[0].Replace("-", " ");
            string subCategory = id.Split("*")[1].Replace("-", " ");

            string select = @"SELECT Url FROM supermarkets WHERE Category='{0}' AND SubCategory='{1}'";

            List<Supermarket> supermarket = DBUtl.GetList<Supermarket>(select, category, subCategory);
            string url = supermarket[0].Url;

            HtmlWeb web = new HtmlWeb();
            var htmlDocument = web.Load(url);
            var products = htmlDocument.DocumentNode.SelectNodes("//*");

            string str = "";

            if (products != null)
            {
                foreach (var product in products)
                {
                    str += SetUCase(product.InnerText.Replace("&amp;", "&"));
                }
            }

            ViewData["Results"] = str;

            return PartialView("_ResultTable");
        }

        public static string SetUCase(string unformattedString)
        {
            string formattedString = "";

            foreach (var s in unformattedString.Split(" "))
            {
                if (s.Length == 0)
                {
                    formattedString += s;
                }
                else if (s.Length == 1)
                {
                    formattedString += char.ToUpper(s[0]);
                }
                else
                {
                    formattedString += char.ToUpper(s[0]) + s.Substring(1);
                }
                formattedString += " ";
            }
            return formattedString.Trim();
        }
    }
}

Dasher/Controllers/UserController.cs
using Dasher.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dasher.Controllers
{
    [Authorize(AuthenticationSchemes = "UserSecurity")]
    public class UserController : Controller
    {
        private List<User> users = DBUtl.GetList<User>(@"SELECT * FROM users");

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(users);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Details(string username)
        {
            return PartialView("_UserDetails", users.Where(w => w.Username == username).FirstOrDefault());
        }

        [Authorize(Roles = "Admin")]
        public IActionResult UserTable()
        {
            return PartialView("_UserTable", users);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(string id)
        {
            string delete = "DELETE FROM users WHERE Username='{0}'";
            int res = DBUtl.ExecSQL(delete, id);

            if (res == 1)
            {
                TempData["Msg"] = "User deleted!";
                TempData["MsgType"] = "success";
            }
            else
            {
                TempData["Msg"] = DBUtl.DB_Message;
                TempData["MsgType"] = "danger";
            }

            return RedirectToAction("Index");
        }
    }
}

Dasher/Controllers/WebController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dasher.Controllers
{
    [AllowAnonymous]
    [Authorize(AuthenticationSchemes = "UserSecurity")]
    public class WebController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Dasher/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Daily Notes</title>

    <!-- Custom fonts for this template-->
    <link href="~/lib/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/lib/css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="~/lib/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Home" asp-action="Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-wind"></i>
                </div>
                <div class="sidebar-brand-text mx-3">DASHMIN</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Note" asp-action="Index">
                    <i class="fas fa-fw fa-pen"></i>
                    <span>Note</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            @if (User.IsInRole("Admin"))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="User" asp-action="Index">
                        <i class="fas fa-fw fa-user"></i>
                        <span>User</span>
                    </a>
                </li>
            }

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                   aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." aria-label="Search"
                                               aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.Identity.Name</span>
                                <img class="img-profile rounded-circle"
                                     src="~/lib/img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" asp-controller="Web" asp-action="Index">
                                    <i class="fas fa-fighter-jet fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Dasher
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Daily Notes 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" asp-controller="Account" asp-action="Logoff">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/lib/vendor/jquery/jquery.min.js"></script>
    <script src="~/lib/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/lib/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/lib/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/lib/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/lib/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/lib/js/demo/datatables-demo.js"></script>

    @RenderSection("ScriptSection", false)

</body>

</html>

Dasher/Views/Shared/_ResultTable.cshtml
<h6>@ViewData["Results"]</h6>

Dasher/Views/Shared/_SourceLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Daily Notes</title>

    <!-- Custom fonts for this template-->
    <link href="~/lib/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/lib/css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="~/lib/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Source" asp-action="Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-list"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SOURCE</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Source" asp-action="Supermarket">
                    <i class="fas fa-fw fa-draw-polygon"></i>
                    <span>Supermarket</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                   aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." aria-label="Search"
                                               aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.Identity.Name</span>
                                <img class="img-profile rounded-circle"
                                     src="~/lib/img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" asp-controller="Web" asp-action="Index">
                                    <i class="fas fa-fighter-jet fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Dasher
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Daily Notes 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" asp-controller="Account" asp-action="Logoff">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/lib/vendor/jquery/jquery.min.js"></script>
    <script src="~/lib/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/lib/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/lib/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/lib/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/lib/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/lib/js/demo/datatables-demo.js"></script>

    @RenderSection("ScriptSection", false)

</body>

</html>

Dasher/Views/Shared/_UserDetails.cshtml
@model User

<header class="panel-heading">User Details</header>
<h3>@Model.Fullname</h3>
<a class="btn btn-primary btn-sm" onclick="return LoadUserTable()">Back</a>